Repository Alfresco/alfresco-helm-charts, pull requests merged in 2023-03, with the labels that each got.

#14 Document basic repository layout and workflows
  README.md
Labels: PR: reviewed-approved

#13 Fix updatecli warning about pr action
  updatecli.d/alfresco-common.tpl
Labels: PR: reviewed-approved

#15 OPSEXP-1853: migrate search-service
  .gitignore
  charts/alfresco-search-service/Chart.lock
  charts/alfresco-search-service/Chart.yaml
  charts/alfresco-search-service/README.md
  charts/alfresco-search-service/README.md.gotmpl
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.lock
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.yaml
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/README.md
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/README.md.gotmpl
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/templates/_helpers.tpl
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/templates/config.yaml
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/templates/deployment.yaml
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/templates/ingress.yaml
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/templates/service.yaml
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/tests/deployment_test.yaml
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/values.yaml
  charts/alfresco-search-service/ci/default-values.yaml
  charts/alfresco-search-service/templates/NOTES.txt
  charts/alfresco-search-service/templates/_helpers.tpl
  charts/alfresco-search-service/templates/config.yaml
  charts/alfresco-search-service/templates/deployment.yaml
  charts/alfresco-search-service/templates/ingress.yaml
  charts/alfresco-search-service/templates/pvc.yaml
  charts/alfresco-search-service/templates/secret-ingress.yaml
  charts/alfresco-search-service/templates/secret-solr-jtoolopt.yaml
  charts/alfresco-search-service/templates/service.yaml
  charts/alfresco-search-service/tests/config_test.yaml
  charts/alfresco-search-service/tests/deployment_test.yaml
  charts/alfresco-search-service/tests/ingress_test.yaml
  charts/alfresco-search-service/tests/secret-ingress_test.yaml
  charts/alfresco-search-service/tests/secret-solr-jtoolopt_test.yaml
  charts/alfresco-search-service/tests/values/ingress.yaml
  charts/alfresco-search-service/tests/values/test_values.yaml
  charts/alfresco-search-service/values.yaml
Labels: PR: reviewed-approved

#16 OPSEXP-1881 KinD tests with latest 1.24 tag
  .github/workflows/lint-test.yaml
Labels: PR: unreviewed

#17 OPSEXP-1853: move named template back in chart
  charts/alfresco-search-service/Chart.yaml
  charts/alfresco-search-service/README.md
  charts/alfresco-search-service/templates/_helpers.tpl
Labels: PR: reviewed-approved

#18 OPSEXP-1853: remove resource naming related named templates
  charts/alfresco-common/Chart.yaml
  charts/alfresco-common/README.md
  charts/alfresco-common/templates/_helpers-search.tpl
Labels: PR: reviewed-approved

#19 OPSEXP-1853: fix repository config support for insight engine
  charts/alfresco-search-service/Chart.lock
  charts/alfresco-search-service/Chart.yaml
  charts/alfresco-search-service/README.md
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.lock
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/Chart.yaml
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/README.md
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/templates/_helpers.tpl
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/templates/config.yaml
  charts/alfresco-search-service/charts/alfresco-insight-zeppelin/tests/config_test.yaml
  charts/alfresco-search-service/tests/resources_test.yaml
Labels: PR: partially-approved

#22 OPSEXP-1954: need an acs-deployment friendly fallback url
  charts/alfresco-sync-service/Chart.lock
  charts/alfresco-sync-service/Chart.yaml
  charts/alfresco-sync-service/README.md
  charts/alfresco-sync-service/ci/default-values.yaml
  charts/alfresco-sync-service/templates/_helpers-db.tpl
  charts/alfresco-sync-service/templates/_helpers-mq.tpl
  charts/alfresco-sync-service/tests/database_test.yaml
  charts/alfresco-sync-service/tests/deployment-syncservice_test.yaml
  charts/alfresco-sync-service/tests/mq_test.yaml
  charts/alfresco-sync-service/values.yaml
Labels: PR: reviewed-approved

#23 OPSPEXP-1854: add a repo helper usable from parent chart
  charts/alfresco-sync-service/Chart.yaml
  charts/alfresco-sync-service/README.md
  charts/alfresco-sync-service/templates/_helpers.tpl
  charts/alfresco-sync-service/templates/config-syncservice.yaml
  charts/alfresco-sync-service/tests/repo_test.yaml
  charts/alfresco-sync-service/values.yaml
Labels: PR: partially-approved

#24 OPSEXP-1854: Add missing service label selector
  charts/alfresco-sync-service/Chart.yaml
  charts/alfresco-sync-service/README.md
  charts/alfresco-sync-service/templates/svc-syncservice.yaml
Labels: PR: reviewed-approved

#25 OPSEXP-1854: provide better default for test backend db
  charts/alfresco-sync-service/Chart.yaml
  charts/alfresco-sync-service/README.md
  charts/alfresco-sync-service/values.yaml
Labels: PR: unreviewed

#27 OPSEXP-2032 add support for k8s 1.25 and kubeconform pre-commit
  .github/workflows/lint-test.yaml
  .github/workflows/pre-commit.yaml
  .pre-commit-config.yaml
  Brewfile
  README.md
  charts/alfresco-search-enterprise/Chart.lock
  charts/alfresco-search-enterprise/Chart.yaml
  charts/alfresco-search-enterprise/README.md
  charts/alfresco-search-enterprise/values.yaml
Labels: PR: reviewed-approved
